const express = require('express');
const router = express.Router(); // initialize router
const createUser=require('../controller/User/createUser')
const createMovie=require('../controller/movie/addMovie')
const addActor=require('../controller/Person/addPerson')
const getUser=require('../controller/User/login')
const getMovie=require('../controller/movie/getMovie')
const listFilter=require('../controller/filter/filterActors')
const getAllMovies=require('../controller/movie/getAllMovies')
const createWatchlist=require('../controller/User/createWatchlist')
const createFavList=require('../controller/User/createFavList')
const getWatchList=require('../controller/User/getWatchList')
const getFavList=require('../controller/User/getFavList')
const delActor=require('../controller/Person/deletePerson')
const delMovie=require('../controller/movie/deleteMovie')
const addReview=require('../controller/User/addReview')
const editMovie=require('../controller/movie/editMovie')
const movieFilter=require('../controller/filter/movieFilter')
const editActor=require('../controller/Person/editPerson')
const {signUpValidation,filterValidation,filterActors,addMovie,editMovies,addPerson}=require('../controller/validations/validation')
//const filterValidation=require('../controller/validations/validation')

router.post('/movieadd' ,createMovie)
router.post('/signup',signUpValidation,createUser)
router.post('/login',getUser)
router.post('/addactors',addPerson,addActor)
router.get('/getmovie/:movieName',getMovie)
router.get('/getallmovies',getAllMovies)
router.post('/addwatchlist/:movieName/:userName',createWatchlist)
router.post('/addfavlist/:movieName/:userName',createFavList)
router.get('/getwatchlist/:userName',getWatchList)
router.get('/getfavList/:userName',getFavList)
router.delete('/deleteperson/:name',delActor)
router.delete('/deletemovie/:name',delMovie)
router.post('/addreview/:movieName',addReview)
router.get('/listfilter/:query?',filterActors,listFilter)
router.get('/moviefilter/:query?',filterValidation,movieFilter)
router.put('/editmovie/:movieName',editMovies,editMovie)
router.put('/editactor/:name',editActor)
module.exports=router