const express = require('express');
const router = express.Router(); // initialize router
const createUser=require('../controller/User/createUser')
const createMovie=require('../controller/movie/Addmovie')
const addActor=require('../controller/Actor/Addactor')
const getUser=require('../controller/User/login')
const getMovie=require('../controller/movie/getMovie')
const listFilter=require('../controller/Filters/ListFilter')
const getAllMovies=require('../controller/movie/getAllMovies')
const createWatchlist=require('../controller/User/CreateWatchlist')
const createFavList=require('../controller/User/createFavList')
const getWatchList=require('../controller/User/getWatchList')
const getFavList=require('../controller/User/getFavList')
const delActor=require('../controller/Actor/deleteActor')
const delMovie=require('../controller/movie/deleteMovie')
const addReview=require('../controller/User/addReiew')
const editMovie=require('../controller/movie/editMovie')
const movieFilter=require('../controller/Filters/movieFilter')


router.post('/movieadd',createMovie)
router.post('/signup',createUser)
router.post('/login',getUser)
router.post('/addactors',addActor)
router.get('/getmovie/:movieId',getMovie)
//router.get('/filteractors/:movie',listFilter)
router.get('/getallmovies',getAllMovies)
router.post('/addwatchlist/:movieName',createWatchlist)
router.post('/addfavlist/:movieName',createFavList)
router.get('/getwatchlist',getWatchList)
router.get('/getfavList',getFavList)
router.delete('/deleteperson/:name',delActor)
router.delete('/deletemovie/:name',delMovie)
router.post('/addreview/:movieName',addReview)
router.get('/listfilter/:query?',listFilter)
router.get('/moviefilter/:query?',movieFilter)
router.put('/editmovie/:movieName',editMovie)
module.exports=router